server:
  port: 8763
spring:
  application:
    name: consumer-sentinel-8763
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080