server:
  port: 8003
spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/clouddb2020?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username : root
    password : root
    driver-class-name : com.mysql.jdbc.Driver
    type : com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      force-response: true
mybatis:
  type-aliases-package : com.zzs.springcloud.entities
  mapper-locations : classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8003



